pipeline {
    agent any
    
    parameters {
      string(name: 'inventory', defaultValue: 'dev',  description: 'This is the inventory file for the environment to deploy configuration')
    }

  stages {
    stage('SCM Checkout') {
      steps {
        script {
          git branch: 'main', credentialsId: 'jenk', url: 'https://github.com/rondrae/ansible-project.git'
        }
      }
    }

    stage('Execute Ansible') {
      steps {
        script {
          ansiblePlaybook credentialsId: 'rondrae-jenkins-key', disableHostKeyChecking: true, installation: 'ansible', inventory: '${inventory}', playbook: 'playbook/playbook.yml', vaultTmpPath: ''
        }
      }
    }

    // stage('Package') {
    //   steps {
    //     script {
    //       sh 'echo "Package Stage"'
    //     }
    //   }
    // }

    // stage('Deploy') {
    //   steps {
    //     script {
    //       sh 'echo "Deploy Stage"'
    //     }
    //   }
    // } 

    // stage('Clean up') {
    //   steps {
    //     script {
    //       sh 'echo "Clean up Stage"'
    //     }
    //   }
    // }       

    }
    
}