---
- hosts: tooling 
  become: yes
  tasks:
    - name: Install packages
      apt:
        name: "apache2"
        state: "present"
    - name: Start Apache server
      service:
        name: apache2
        state: started
        enabled: True
    - name: Deploy static website
      copy:
        src: ../index.html
        dest: /var/www/html/
    
    # - name: Install PHP
    #   apt: name name={{ item }} update_cache=yes state=latest
    #   with_items:
    #     - zip
    #     - libapache2-mod-php
    #     - phploc
    #     - php-xml
    #     - php-bcmath
    #     - php-bz2
    #     - php-intl
    #     - php-gd
    #     - php-mbstring
    #     - php-mysql
    #     - php-zip
        